name: Windows Build

on:
  workflow_call:

jobs:
  win-build:
    runs-on: [self-hosted, windows]
    
    strategy:
      fail-fast: false
      matrix:
        build-type: [Release, Debug]
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        repository: novusengine/AssetConverter

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive

    - name: Premake
      run: |
        premake5 vs2022

    - name: Build
      run: |
        msbuild /m /p:Configuration=${{ matrix.build-type }} Build/AssetConverter.sln

    - name: Upload AssetConverter artifact
      uses: actions/upload-artifact@v4
      with:
        name: AssetConverter_${{ matrix.build-type }}
        path: |
          Build/Bin/AssetConverter/${{ matrix.build-type }}/AssetConverter-App.exe
